Revert "Update blobs from SQ1D.211205.016.A1"
This reverts commit 5d47f126c7f06c67aeb9184def1809b49bd1994f.

I'm not exactly sure, why SysUiStatsLog wasn't updated in our vendor tree.
To get around the problem, we have to go back to the older state.

12-20 11:09:36.512  5637  5637 E AndroidRuntime: Process: com.android.systemui, PID: 5637
12-20 11:09:36.512  5637  5637 E AndroidRuntime: java.lang.NoSuchMethodError: No static method write(IIIIIIIIIIII)V in class Lcom/android/systemui/shared/system/SysUiStatsLog; or its super classes (declaration of 'com.android.systemui.shared.system.SysUiStatsLog' appears in /system_ext/priv-app/SystemUI/SystemUI.apk)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at com.google.android.systemui.smartspace.BcSmartspaceLogger.log(Unknown Source:34)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at com.google.android.systemui.smartspace.BcSmartspaceView.logSmartspaceEvent(Unknown Source:102)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at com.google.android.systemui.smartspace.BcSmartspaceView.onSmartspaceTargetsUpdated(Unknown Source:123)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at com.google.android.systemui.smartspace.BcSmartspaceDataProvider.registerListener(Unknown Source:7)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at com.google.android.systemui.smartspace.BcSmartspaceView.registerDataProvider(Unknown Source:18)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at com.android.systemui.statusbar.lockscreen.LockscreenSmartspaceController.buildView(LockscreenSmartspaceController.kt:174)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at com.android.systemui.statusbar.lockscreen.LockscreenSmartspaceController.buildAndConnectView(LockscreenSmartspaceController.kt:153)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at com.android.keyguard.KeyguardClockSwitchController.onViewAttached(KeyguardClockSwitchController.java:203)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at com.android.systemui.util.ViewController$1.onViewAttachedToWindow(ViewController.java:52)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at android.view.View.dispatchAttachedToWindow(View.java:20768)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3490)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2616)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2129)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8671)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1120)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:926)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:859)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1105)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7880)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
12-20 11:09:36.512  5637  5637 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)